### PR TITLE
Update documentation framework(docusaurus) version and add navigation bar

### PR DESCRIPTION
**Pull request by Pana**
1. Add a navigation bar
2. Update docusaurus version to 2.0.0-alpha.73
3. Remove submodule js-sdk, go-sdk, portal. Replace them with links
4. Reorg doc folder

### CODE REVIEW

**Review by yqrashawn — CHANGES_REQUESTED** [review]
image
failed to build on clean install

**Comment by Pana** [comment]
This is because one of `conflux-doc`'s document has an invalid link. I have updated that markdown doc.
If you use the newest `conflux-doc` the build will success

**Comment by yqrashawn** [comment]
Then update the submodule and sync to the upstream.

Why do we remove the algolia support here?

**Comment by Pana** [comment]
The submodule has been updated, also the algolia config

**Review by yqrashawn — APPROVED** [review]

**Pull request merged**
